const PINYIN_GROUPS = {
  a: '阿啊',
  ai: '爱艾埃',
  an: '安岸',
  ang: '昂',
  ao: '奥澳',
  ba: '八巴霸',
  bai: '百柏佰',
  ban: '班般板办',
  bang: '邦帮',
  bao: '宝保包报',
  bei: '北贝备',
  ben: '本',
  bi: '比必币',
  bian: '边遍',
  biao: '标',
  bing: '并',
  bo: '博波播',
  bu: '布部',
  cai: '财才采',
  can: '灿',
  cang: '仓',
  ce: '策',
  cha: '查',
  chan: '产',
  chang: '长昌',
  chao: '超',
  che: '车',
  chen: '辰晨陈',
  cheng: '成城程承',
  chi: '驰',
  chong: '崇',
  chuang: '创',
  ci: '磁',
  cloud: '云',
  da: '大达',
  dai: '代',
  dan: '丹',
  dao: '道',
  de: '德',
  deng: '登',
  di: '迪地帝',
  dian: '电点',
  ding: '鼎',
  dong: '东动',
  dou: '都',
  du: '度都',
  dun: '顿',
  duo: '多',
  er: '二尔',
  fa: '发法',
  fang: '方',
  fei: '飞非菲',
  feng: '峰丰锋',
  fu: '福服富',
  gai: '盖',
  gang: '港刚',
  gao: '高',
  ge: '格歌',
  gong: '工公供',
  guang: '广光',
  guo: '国果',
  hai: '海',
  han: '汉瀚',
  hang: '航',
  hao: '浩号',
  he: '合和河',
  heng: '恒',
  hong: '宏鸿洪红',
  hua: '华化',
  huan: '环寰',
  huang: '黄',
  hui: '汇惠慧',
  huo: '火',
  ji: '机极基吉技际集纪济计',
  jia: '嘉佳家加',
  jian: '建健简',
  jiang: '江疆',
  jie: '捷杰界',
  jin: '金津进',
  jing: '京晶精景',
  ju: '聚巨',
  kai: '开凯',
  kang: '康',
  ke: '科客克',
  kong: '空',
  kuai: '快',
  kuan: '宽',
  lai: '来',
  lan: '蓝澜',
  lang: '朗',
  lao: '老',
  le: '乐',
  lei: '雷',
  leng: '冷',
  li: '力立利理里励',
  lian: '联连链',
  liang: '量良亮',
  ling: '凌灵领',
  liu: '流六柳',
  long: '龙隆',
  lu: '陆路录',
  ma: '码马',
  mai: '麦',
  man: '曼',
  mao: '贸',
  mei: '美',
  meng: '盟梦',
  mi: '米',
  min: '敏闽',
  ming: '明名',
  nan: '南',
  neng: '能',
  niu: '牛',
  nuo: '诺',
  ou: '欧',
  pai: '派',
  peng: '鹏',
  pu: '普',
  qi: '企奇启琪期',
  qian: '千前乾',
  qiang: '强',
  qiao: '桥',
  qing: '青清擎',
  qu: '区趣渠',
  quan: '全权',
  ran: '然',
  ren: '人仁',
  rong: '融荣',
  rui: '瑞睿',
  san: '三',
  se: '色',
  shan: '山善',
  shang: '上商尚',
  shao: '绍',
  shen: '深申神',
  sheng: '盛生胜省',
  shi: '市世时实石仕士',
  shu: '数树',
  shuang: '双',
  shui: '水',
  si: '思斯司丝',
  su: '速苏',
  tai: '泰台太',
  tang: '唐',
  te: '特',
  teng: '腾',
  tian: '天',
  tie: '铁',
  tong: '通同桐',
  tu: '图',
  tuo: '拓',
  wan: '万湾',
  wang: '网旺',
  wei: '维微威为伟',
  wen: '文',
  wu: '物五',
  xi: '西希息喜系',
  xia: '夏',
  xian: '先线显贤',
  xiang: '翔湘祥享',
  xiao: '小晓',
  xin: '新信芯',
  xing: '星兴行',
  xun: '讯迅寻',
  ya: '亚雅',
  yan: '研延言',
  yang: '阳洋扬',
  yao: '耀',
  ye: '业',
  yi: '一易亿意翼益宜盈',
  yin: '银音',
  ying: '英盈影',
  yong: '永',
  you: '优友',
  yu: '宇雨域裕誉',
  yuan: '元源远',
  yun: '云运',
  zai: '载',
  ze: '泽',
  zeng: '增',
  zhan: '展站',
  zhang: '章张',
  zhao: '兆招',
  zhe: '浙',
  zhen: '圳真臻',
  zheng: '正政',
  zhi: '智志至',
  zhong: '中众',
  zhou: '州舟洲',
  zhu: '珠主',
  zhuo: '卓',
  zi: '资子',
  zong: '纵',
}

const CHAR_PINYIN = Object.entries(PINYIN_GROUPS).reduce((acc, [pinyin, chars]) => {
  for (const char of chars) acc[char] = pinyin
  return acc
}, {})

function normalize(value) {
  return String(value || '')
    .toLowerCase()
    .replace(/\s+/g, '')
}

function toPinyin(value) {
  const syllables = []
  for (const char of String(value || '')) {
    const pinyin = CHAR_PINYIN[char]
    if (pinyin) syllables.push(pinyin)
  }
  return {
    full: syllables.join(''),
    initials: syllables.map((item) => item[0]).join(''),
  }
}

export function buildPinyinSearchText(values) {
  const raw = values.filter(Boolean).join(' ')
  const pinyin = toPinyin(raw)
  return normalize([raw, pinyin.full, pinyin.initials].join(' '))
}

export function pinyinOptionFilter(pattern, option) {
  const keyword = normalize(pattern)
  if (!keyword) return true
  return normalize(option?.searchText || option?.label).includes(keyword)
}
